'use client';
import { useEffect, useMemo, useState } from 'react';

type Vlan={id:number;name:string;color:string};
type Port={number:number;status:'up'|'down';speed?:string;vlan:number;tagged?:number[];poe?:string;device?:string;ip?:string;mac?:string;drops:number;errors:number;optical?:string;media:'copper'|'sfp'};
type NetworkSwitch={id:string;name:string;model:string;ip:string;location:string;uptime:string;ports:Port[]};
const vlans:Vlan[]=[{id:1,name:'Management',color:'#8b98a9'},{id:10,name:'Dante Primary',color:'#26c6a2'},{id:20,name:'Video',color:'#ff9d42'},{id:30,name:'Control',color:'#8bc65a'},{id:40,name:'NDI',color:'#b281e8'}];
const devices=['Rio3224-D2','QL5 Console','PIXERA-01','Disguise RX','Lighting Node','Rack Mac Mini','NDI Camera','Media Server'];
const makePorts=(count:number,offset=0):Port[]=>Array.from({length:count},(_,i)=>{const n=i+1;const down=n%7===0||n%11===0;const sfp=n>count-4;const vlan=[10,10,20,20,30,1,40][(i+offset)%7];return {number:n,status:down?'down':'up',speed:down?undefined:sfp?'10G':'1G',vlan,tagged:sfp?[10,20,30,40]:undefined,poe:!down&&!sfp?`${(4.1+(n%9)*1.2).toFixed(1)} W`:undefined,device:down?undefined:sfp?`${n%2?'Core':'Stage'} Uplink`:devices[(i+offset)%devices.length],ip:down?undefined:`10.${vlan}.${offset+1}.${100+n}`,mac:down?undefined:`00:1B:44:${(offset+10).toString(16).toUpperCase()}:2A:${n.toString(16).padStart(2,'0').toUpperCase()}`,drops:down?0:n%9===0?124:n%5,errors:down?0:n%13===0?8:0,optical:sfp&&!down?`${(-2.1-(n%3)*.4).toFixed(1)} dBm`:undefined,media:sfp?'sfp':'copper'};});
const initialSwitches:NetworkSwitch[]=[
 {id:'stage-left',name:'Stage Left',model:'M4250-26G4XF-PoE+',ip:'10.1.0.21',location:'Main Stage · Rack A',uptime:'18d 04h',ports:makePorts(24,0)},
 {id:'foh',name:'Front of House',model:'M4350-24X4V',ip:'10.1.0.22',location:'FOH · Network Rack',uptime:'18d 04h',ports:makePorts(24,2)},
 {id:'video-world',name:'Video World',model:'M4250-40G8XF-PoE+',ip:'10.1.0.23',location:'Backstage · Video Rack',uptime:'12d 19h',ports:makePorts(16,4)},
 {id:'stage-right',name:'Stage Right',model:'M4250-26G4XF-PoE+',ip:'10.1.0.24',location:'Main Stage · Rack B',uptime:'7d 11h',ports:makePorts(12,1)}
];
const vf=(id:number)=>vlans.find(v=>v.id===id)??vlans[0];

export default function Home(){
 const [switches,setSwitches]=useState(initialSwitches);const [selectedId,setSelectedId]=useState<string|null>(null);const [query,setQuery]=useState('');const [selectedPort,setSelectedPort]=useState<Port|null>(null);const [pendingVlan,setPendingVlan]=useState<number|null>(null);const [notice,setNotice]=useState('');
 const [dataSource,setDataSource]=useState<'connecting'|'live'|'demo'>('connecting');const [subnet,setSubnet]=useState('10.1.0.0/24');const [lastUpdated,setLastUpdated]=useState<string|null>(null);
 const selected=switches.find(s=>s.id===selectedId)??null;
 const matches=useMemo(()=>switches.filter(s=>`${s.name} ${s.model} ${s.ip} ${s.location}`.toLowerCase().includes(query.toLowerCase())),[switches,query]);
 const ports=selected?.ports.filter(p=>`${p.number} ${p.device??''} ${p.ip??''} ${vf(p.vlan).name}`.toLowerCase().includes(query.toLowerCase()))??[];
 async function loadLive(){try{const host=window.location.hostname||'localhost';const response=await fetch(`http://${host}:8787/api/switches`,{cache:'no-store'});if(!response.ok)throw new Error('Collector unavailable');const data=await response.json() as {status:string;subnet:string;lastUpdated:string|null;switches:NetworkSwitch[]};setSubnet(data.subnet);setLastUpdated(data.lastUpdated);if(data.switches.length){setSwitches(data.switches);setDataSource('live')}else if(data.status==='online'){setSwitches([]);setDataSource('live')}}catch{setDataSource('demo')}}
 async function requestScan(){try{const host=window.location.hostname||'localhost';await fetch(`http://${host}:8787/api/scan`,{method:'POST'});setNotice('Network scan started');setTimeout(()=>void loadLive(),2500)}catch{setNotice('Collector is not connected')}setTimeout(()=>setNotice(''),3000)}
 useEffect(()=>{void loadLive();const timer=window.setInterval(()=>void loadLive(),30000);return()=>window.clearInterval(timer)},[]);
 function confirmVlan(){if(!selected||!selectedPort||pendingVlan===null)return;setSwitches(all=>all.map(s=>s.id!==selected.id?s:{...s,ports:s.ports.map(p=>p.number===selectedPort.number?{...p,vlan:pendingVlan}:p)}));setSelectedPort(p=>p?{...p,vlan:pendingVlan}:p);setNotice(`Port ${selectedPort.number} moved to VLAN ${pendingVlan}`);setPendingVlan(null);setTimeout(()=>setNotice(''),3000)}
 return <main className="app-shell">
  <header className="topbar"><button className="brand" onClick={()=>{setSelectedId(null);setQuery('')}}><span className="brand-mark">N</span><span><strong>NETGEAR</strong><small>AV NETWORK</small></span></button><div className={`network-state ${dataSource}`}><span className="pulse"/> {dataSource==='live'?`Live · ${subnet}`:dataSource==='connecting'?'Connecting…':'Demo data · collector offline'}</div><button className="icon-button" aria-label="Open server settings" onClick={()=>window.open(`http://${window.location.hostname||'localhost'}:8787/setup`,'_blank')}>⚙</button></header>
  {!selected?<>
   <section className="hero"><div><p className="eyebrow">NETWORK OVERVIEW</p><h1>Your switches</h1><p className="subtitle">{dataSource==='live'?`Live SNMPv3 results from ${subnet}${lastUpdated?` · updated ${new Date(lastUpdated).toLocaleTimeString()}`:''}`:'Select a switch to inspect its ports and connected equipment.'}</p></div><div className="stats"><div><span className="stat-dot"/><strong>{switches.length}</strong><small>ONLINE</small></div><div><strong>{switches.flatMap(s=>s.ports).filter(p=>p.status==='up').length}</strong><small>ACTIVE PORTS</small></div><div><strong>{vlans.length}</strong><small>VLANS</small></div></div></section>
   <section className="controls"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search switches by name, model or IP…"/></label><button className="scan-button" onClick={requestScan}>↻ Scan network</button></section>
   <section className="switch-grid">{matches.map(sw=><button className="switch-picker" key={sw.id} onClick={()=>{setSelectedId(sw.id);setQuery('')}}><header><div><span className="online"><i/>ONLINE</span><h2>{sw.name}</h2><p>{sw.location}</p></div><span className="chevron">›</span></header><div className="mini-chassis"><div className="mini-brand">NETGEAR <span>{sw.model.split('-')[0]}</span></div><div className="mini-ports" style={{gridTemplateColumns:`repeat(${Math.ceil(sw.ports.length/2)}, minmax(0, 1fr))`}}>{sw.ports.map(p=><i key={p.number} title={`Port ${p.number} · VLAN ${p.vlan}`} style={{'--port-color':vf(p.vlan).color} as React.CSSProperties} className={p.status}/>)}</div></div><footer><span><b>{sw.ports.filter(p=>p.status==='up').length}</b> active</span><span><b>{sw.ports.length}</b> total ports</span><span><code>{sw.ip}</code></span></footer></button>)}</section>
  </>:<>
   <section className="detail-head"><button className="back" onClick={()=>{setSelectedId(null);setSelectedPort(null);setQuery('')}}>← All switches</button><div className="detail-title"><div><span className="online"><i/>ONLINE</span><h1>{selected.name}</h1><p>{selected.model} · {selected.ip} · Uptime {selected.uptime}</p></div><button className="refresh" onClick={requestScan}>↻ Refresh</button></div></section>
   <section className="chassis-card"><div className="chassis-label"><b>NETGEAR</b><span>{selected.model}</span></div><div className="chassis-ports" style={{gridTemplateColumns:`repeat(${Math.ceil(selected.ports.length/2)}, minmax(0, 1fr))`}}>{selected.ports.map(p=><button key={p.number} onClick={()=>setSelectedPort(p)} className={`${p.status} ${selectedPort?.number===p.number?'selected':''}`} style={{'--port-color':vf(p.vlan).color} as React.CSSProperties}><small>{p.number}</small><span className="socket"><i/><i/><i/><i/></span><em/></button>)}</div><div className="chassis-leds"><span><i/>PWR</span><span><i/>FAN</span><span><i/>STACK</span></div></section>
   <aside className="vlan-key"><strong>PORT COLOR</strong>{vlans.map(v=><span key={v.id}><i style={{background:v.color}}/>{v.id} · {v.name}</span>)}</aside>
   <section className="port-section"><div className="section-bar"><div><p className="eyebrow">PORT INVENTORY</p><h2>Ports & connected equipment</h2></div><label className="search compact"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ports, device or IP…"/></label></div><div className="port-list">{ports.map(p=><button key={p.number} onClick={()=>setSelectedPort(p)} className="port-row"><span className="port-number" style={{'--port-color':vf(p.vlan).color} as React.CSSProperties}><i/>{p.number}</span><span className="device-cell"><strong>{p.device??'Nothing connected'}</strong><small>{p.ip??'—'} {p.mac?`· ${p.mac}`:''}</small></span><span className="metric"><small>LINK</small><b className={p.status}>{p.status==='up'?p.speed:'Down'}</b></span><span className="metric"><small>VLAN</small><b><i style={{background:vf(p.vlan).color}}/>{p.vlan} · {vf(p.vlan).name}</b></span><span className="metric"><small>DROPS / ERRORS</small><b className={p.errors?'warn':''}>{p.drops} / {p.errors}</b></span><span className="metric optical"><small>{p.media==='sfp'?'OPTICAL RX':'POE DRAW'}</small><b>{p.optical??p.poe??'—'}</b></span><span className="row-arrow">›</span></button>)}</div></section>
  </>}
  {selected&&selectedPort&&<div className="modal-backdrop" onMouseDown={()=>setSelectedPort(null)}><section className="port-sheet" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelectedPort(null)} aria-label="Close">×</button><div className="sheet-handle"/><p className="eyebrow">{selected.name.toUpperCase()}</p><h2>Port {selectedPort.number}</h2><div className="detail-status"><span className={`big-dot ${selectedPort.status}`}/><strong>{selectedPort.status==='up'?'Connected':'Not connected'}</strong><span>{selectedPort.speed??'Link down'}</span></div><dl><div><dt>Device</dt><dd>{selectedPort.device??'—'}</dd></div><div><dt>IP address</dt><dd>{selectedPort.ip??'—'}</dd></div><div><dt>MAC address</dt><dd>{selectedPort.mac??'—'}</dd></div><div><dt>Packet drops</dt><dd className={selectedPort.drops>50?'warn':''}>{selectedPort.drops.toLocaleString()}</dd></div><div><dt>Port errors</dt><dd className={selectedPort.errors?'warn':''}>{selectedPort.errors}</dd></div><div><dt>{selectedPort.media==='sfp'?'Optical receive':'PoE draw'}</dt><dd>{selectedPort.optical??selectedPort.poe??'—'}</dd></div></dl><div className="vlan-control"><label htmlFor="vlan">Native VLAN</label><select id="vlan" value={selectedPort.vlan} disabled={dataSource==='live'} onChange={e=>setPendingVlan(Number(e.target.value))}>{vlans.map(v=><option value={v.id} key={v.id}>VLAN {v.id} · {v.name}</option>)}</select><small>{dataSource==='live'?'Live mode is read-only while SNMP results are being verified.':'Changing a VLAN can disconnect the attached device.'}</small></div></section></div>}
  {pendingVlan!==null&&selected&&selectedPort&&<div className="confirm-backdrop"><section className="confirm"><span className="warning">!</span><h2>Change port VLAN?</h2><p>Port {selectedPort.number} on <strong>{selected.name}</strong> will move from VLAN {selectedPort.vlan} to <strong>VLAN {pendingVlan} · {vf(pendingVlan).name}</strong>.</p><div className="warning-copy"><b>Connection may be interrupted</b><span>The connected device could become unreachable if its network settings do not match.</span></div><div className="confirm-actions"><button onClick={()=>setPendingVlan(null)}>Cancel</button><button className="danger" onClick={confirmVlan}>Confirm change</button></div></section></div>}
  {notice&&<div className="toast">✓ {notice}</div>}
 </main>
}
