'use client';
import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import {modelLayout,panelPorts} from '../lib/netgear-models';

type Vlan={id:number;name:string;color:string};
type Port={number:number;bridgePort?:number;interface?:string;description?:string;status:'up'|'down';speed?:string;vlan:number;tagged?:number[];poe?:string;device?:string;neighborPort?:string;ip?:string;mac?:string;learnedMacs?:string[];drops:number;errors:number;optical?:string;media:'copper'|'sfp';usageMbps?:number};
type NetworkSwitch={id:string;name:string;model:string;ip:string;location:string;uptime:string;ports:Port[]};
type SchemeProfile={id:number;name:string;color?:string};
type ColorScheme={sourceIp:string|null;sourceName:string|null;updatedAt:string|null;profiles:SchemeProfile[]};
const colorFor=(id:number)=>`hsl(${Math.round((Math.abs(id)*137.508)%360)} 68% 58%)`;
const outlineFor=(color:string)=>{const match=color.match(/^#([0-9a-f]{6})$/i);if(!match)return color;const value=Number.parseInt(match[1],16),channels=[value>>16,(value>>8)&255,value&255].map(channel=>{const normalized=channel/255;return normalized<=.04045?normalized/12.92:((normalized+.055)/1.055)**2.4});return channels[0]*.2126+channels[1]*.7152+channels[2]*.0722<.2?'#ffffff':color};
const normalizeName=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]/g,'');
const usageLabel=(value?:number)=>value===undefined?'Sampling…':value<.01?'<0.01 Mbps':value<1000?`${value.toFixed(value<10?2:1)} Mbps`:`${(value/1000).toFixed(2)} Gbps`;
function Topology({switches,onSelect,lastUpdated,vlanFor}:{switches:NetworkSwitch[];onSelect:(id:string)=>void;lastUpdated:string|null;vlanFor:(id:number)=>Vlan}){
 const stageRef=useRef<HTMLDivElement|null>(null),dragRef=useRef<{id:string;moved:boolean;point:{x:number;y:number}}|null>(null);
 const [savedPositions,setSavedPositions]=useState<Record<string,{x:number;y:number}>>({}),[layoutLoaded,setLayoutLoaded]=useState(false),[zoom,setZoom]=useState(.8);
 const defaultPositions=useMemo(()=>{const columns=Math.min(3,Math.max(1,switches.length));return Object.fromEntries(switches.map((item,index)=>{const column=index%columns,row=Math.floor(index/columns),stagger=row%2&&columns>1?1.5:0;return [item.id,{x:columns===1?20:9+column*15+stagger,y:9+row*9}]}))},[switches]);
 const positions=useMemo(()=>Object.fromEntries(switches.map(item=>[item.id,savedPositions[item.id]??defaultPositions[item.id]])),[switches,savedPositions,defaultPositions]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('netgear-discovery-topology-layout-v2')||'{}'),savedZoom=Number(localStorage.getItem('netgear-discovery-topology-zoom-v1'));if(saved&&typeof saved==='object')setSavedPositions(saved);if(savedZoom>=.5&&savedZoom<=1.5)setZoom(savedZoom)}catch{}setLayoutLoaded(true)},[]);
 useEffect(()=>{if(layoutLoaded){localStorage.setItem('netgear-discovery-topology-layout-v2',JSON.stringify(savedPositions));localStorage.setItem('netgear-discovery-topology-zoom-v1',String(zoom))}},[savedPositions,zoom,layoutLoaded]);
 function moveNode(event:ReactPointerEvent<HTMLButtonElement>,id:string){const drag=dragRef.current,stage=stageRef.current;if(!drag||drag.id!==id||!stage)return;const rect=stage.getBoundingClientRect(),point={x:Math.max(4,Math.min(96,(event.clientX-rect.left)/rect.width*100)),y:Math.max(5,Math.min(95,(event.clientY-rect.top)/rect.height*100))};drag.moved=true;drag.point=point;event.currentTarget.style.left=`${point.x}%`;event.currentTarget.style.top=`${point.y}%`;for(const line of stage.querySelectorAll<SVGLineElement>('line[data-a]')){const a=line.dataset.a,b=line.dataset.b;if(a===id){line.setAttribute('x1',String(point.x));line.setAttribute('y1',String(point.y))}if(b===id){line.setAttribute('x2',String(point.x));line.setAttribute('y2',String(point.y))}}for(const label of stage.querySelectorAll<HTMLElement>('.topology-link-label[data-a]')){const a=label.dataset.a,b=label.dataset.b;if(a!==id&&b!==id)continue;const other=positions[a===id?String(b):String(a)];if(other){label.style.left=`${(point.x+other.x)/2}%`;label.style.top=`${(point.y+other.y)/2}%`}}}
 function finishMove(event:ReactPointerEvent<HTMLButtonElement>){const drag=dragRef.current;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);if(drag?.moved)setSavedPositions(current=>({...current,[drag.id]:drag.point}))}
 const links=useMemo(()=>{const namesMatch=(device:string|undefined,item:NetworkSwitch)=>{const left=normalizeName(device||''),right=normalizeName(item.name);return Boolean(left&&right&&(left.includes(right)||right.includes(left)))};const portKey=(value:string|number|undefined)=>String(value??'unknown').toLowerCase().replace(/^(?:g|xg|ge|xe)/,'').replace(/[^0-9/]/g,'');const found=new Map<string,{a:NetworkSwitch;b:NetworkSwitch;pa:Port;pb?:Port}>();for(const source of switches)for(const port of source.ports){if(port.status!=='up')continue;const target=switches.find(item=>item.id!==source.id&&(item.ip===port.ip||namesMatch(port.device,item)));if(!target)continue;const localKey=portKey(port.interface||port.number),remoteKey=portKey(port.neighborPort);const reverse=target.ports.find(item=>item.status==='up'&&(item.ip===source.ip||namesMatch(item.device,source))&&(!remoteKey||portKey(item.interface||item.number)===remoteKey))||target.ports.find(item=>item.status==='up'&&(item.ip===source.ip||namesMatch(item.device,source)));const endpoints=[`${source.id}:${localKey}`,`${target.id}:${remoteKey||portKey(reverse?.interface||reverse?.number)}`].sort(),key=endpoints.join('|');if(!found.has(key))found.set(key,{a:source,b:target,pa:port,pb:reverse})}return [...found.values()]},[switches]);
 return <>
  <section className="topology-head"><div><p className="eyebrow">LIVE NETWORK MAP</p><h1>Network topology</h1><p className="subtitle">Scroll, zoom and arrange the LLDP map{lastUpdated?` · updated ${new Date(lastUpdated).toLocaleTimeString()}`:''}</p></div><div className="topology-actions"><div className="zoom-controls"><button onClick={()=>setZoom(value=>Math.max(.5,Number((value-.1).toFixed(1))))} aria-label="Zoom out">−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(value=>Math.min(1.5,Number((value+.1).toFixed(1))))} aria-label="Zoom in">+</button></div><button onClick={()=>{setSavedPositions({});setZoom(.8)}} disabled={!Object.keys(savedPositions).length&&zoom===.8}>↺ Reset layout</button><div className="topology-summary"><strong>{links.length}</strong><span>SWITCH LINKS</span><strong>{links.filter(link=>link.pa.media==='sfp'||link.pb?.media==='sfp').length}</strong><span>OPTICAL</span></div></div></section>
  <section className="topology-canvas">{switches.length?<div className="topology-world" style={{width:3600*zoom,height:2400*zoom}}><div className="topology-stage" ref={stageRef} style={{transform:`scale(${zoom})`}}><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{links.map((link,index)=>{const a=positions[link.a.id],b=positions[link.b.id],errors=link.pa.errors+(link.pb?.errors||0);return <line key={`${link.a.id}-${link.pa.number}-${link.b.id}-${link.pb?.number??index}`} data-a={link.a.id} data-b={link.b.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className={errors?'has-errors':''}/>})}</svg>{links.map((link,index)=>{const a=positions[link.a.id],b=positions[link.b.id],errors=link.pa.errors+(link.pb?.errors||0),optical=[link.pa.optical,link.pb?.optical].filter(Boolean).join(' / '),usage=Math.max(link.pa.usageMbps??-1,link.pb?.usageMbps??-1);return <div className={`topology-link-label ${errors?'has-errors':''}`} key={`label-${link.a.id}-${link.pa.number}-${link.b.id}-${link.pb?.number??index}`} data-a={link.a.id} data-b={link.b.id} style={{left:`${(a.x+b.x)/2}%`,top:`${(a.y+b.y)/2}%`}}><strong>P{link.pa.number} ↔ {link.pb?`P${link.pb.number}`:(link.pa.neighborPort||'Remote')}</strong><span>{usageLabel(usage<0?undefined:usage)} · {link.pa.speed||link.pb?.speed||'Link up'}</span>{optical&&<span>RX {optical}</span>}<em>{errors?`${errors.toLocaleString()} errors`:'No errors'}</em></div>})}{switches.map(item=>{const point=positions[item.id],active=item.ports.filter(port=>port.status==='up').length,errors=item.ports.reduce((sum,port)=>sum+port.errors,0),layout=modelLayout(item.model,item.ports.length);return <button key={item.id} className="topology-node" style={{left:`${point.x}%`,top:`${point.y}%`}} onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);dragRef.current={id:item.id,moved:false,point}}} onPointerMove={event=>moveNode(event,item.id)} onPointerUp={finishMove} onPointerCancel={finishMove} onClick={event=>{if(dragRef.current?.id===item.id&&dragRef.current.moved){event.preventDefault();dragRef.current=null;return}dragRef.current=null;onSelect(item.id)}}><span className="topology-drag-handle" aria-hidden="true">⠿</span><span className="topology-node-status"/><strong>{item.name}</strong><small>{item.model} · {item.ip}</small><div className="topology-node-ports" style={{gridTemplateColumns:`repeat(${layout.columns},1fr)`}}>{panelPorts(item.ports,layout.rows).map(port=>{const color=vlanFor(port.vlan).color;return <i key={port.number} className={`${port.status} ${port.media}`} title={`Port ${port.number} · VLAN ${port.vlan} · ${vlanFor(port.vlan).name}`} style={{'--port-color':color,'--port-outline':outlineFor(color)} as React.CSSProperties}/>} )}</div><em>{active} active ports{errors?` · ${errors} errors`:''}</em></button>})}</div></div>:<div className="topology-empty"><span>⌁</span><h2>No topology available</h2><p>Run a network scan to discover switches and LLDP connections.</p></div>}</section>
  <section className="topology-legend"><span><i/> Healthy link</span><span><i className="error"/> Link with errors</span><small>Scroll the canvas, zoom with the controls, and drag switches to save their positions.</small></section>
 </>
}
export default function Home(){
 const [switches,setSwitches]=useState<NetworkSwitch[]>([]);const [selectedId,setSelectedId]=useState<string|null>(null);const [view,setView]=useState<'dashboard'|'topology'>('dashboard');const [query,setQuery]=useState('');const [selectedPort,setSelectedPort]=useState<Port|null>(null);const [notice,setNotice]=useState('');
 const [vlans,setVlans]=useState<Vlan[]>([]);
 const [dataSource,setDataSource]=useState<'connecting'|'live'|'offline'>('connecting');const [subnet,setSubnet]=useState('10.1.0.0/24');const [dashboardAddress,setDashboardAddress]=useState('localhost:3000');const [lastUpdated,setLastUpdated]=useState<string|null>(null);
 const [schemeOpen,setSchemeOpen]=useState(false);const [scheme,setScheme]=useState<ColorScheme>({sourceIp:null,sourceName:null,updatedAt:null,profiles:[]});const [schemePreview,setSchemePreview]=useState<ColorScheme|null>(null);const [schemeSwitch,setSchemeSwitch]=useState('');const [avUsername,setAvUsername]=useState('admin');const [avPassword,setAvPassword]=useState('');const [schemeStatus,setSchemeStatus]=useState<'idle'|'pulling'|'saving'>('idle');const [schemeError,setSchemeError]=useState('');
 const vf=(id:number)=>vlans.find(v=>v.id===id)??{id,name:`VLAN ${id}`,color:colorFor(id)};
 const selected=switches.find(s=>s.id===selectedId)??null;
 const matches=useMemo(()=>{const term=query.trim().toLowerCase();return switches.filter(s=>`${s.name} ${s.model} ${s.ip} ${s.ip.split('.').at(-1)} ${s.location}`.toLowerCase().includes(term))},[switches,query]);
 const ports=selected?.ports.filter(p=>{const term=query.trim().toLowerCase();return `${p.number} ${p.device??''} ${p.ip??''} ${p.ip?.split('.').at(-1)??''} ${vf(p.vlan).name}`.toLowerCase().includes(term)})??[];
 async function loadLive(){try{const host=window.location.hostname||'localhost';const response=await fetch(`http://${host}:8787/api/switches`,{cache:'no-store'});if(!response.ok)throw new Error('Collector unavailable');const data=await response.json() as {status:string;subnet:string;dashboardAddress?:string;dashboardPort?:number;lastUpdated:string|null;vlans?:Array<Partial<Vlan>&Pick<Vlan,'id'|'name'>>;switches:NetworkSwitch[]};setSubnet(data.subnet);setDashboardAddress(`${data.dashboardAddress||host}:${data.dashboardPort||3000}`);setLastUpdated(data.lastUpdated);setVlans((data.vlans??[]).map(v=>({...v,color:v.color||colorFor(v.id)})));setSwitches(data.switches??[]);setDataSource('live')}catch{setSwitches([]);setVlans([]);setSelectedId(null);setDataSource('offline')}}
 async function requestScan(){try{const host=window.location.hostname||'localhost';await fetch(`http://${host}:8787/api/scan`,{method:'POST'});setNotice('Network scan started');setTimeout(()=>void loadLive(),2500)}catch{setNotice('Collector is not connected')}setTimeout(()=>setNotice(''),3000)}
 async function loadScheme(){try{const host=window.location.hostname||'localhost';const response=await fetch(`http://${host}:8787/api/color-scheme`,{cache:'no-store'});if(response.ok)setScheme(await response.json())}catch{}}
 async function pullScheme(){setSchemeError('');setSchemePreview(null);setSchemeStatus('pulling');try{const host=window.location.hostname||'localhost';const response=await fetch(`http://${host}:8787/api/color-scheme/pull`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({switchIp:schemeSwitch,username:avUsername,password:avPassword})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not pull the AV color scheme');setSchemePreview(result);setAvPassword('')}catch(error){setSchemeError(error instanceof Error?error.message:'Could not pull the AV color scheme')}finally{setSchemeStatus('idle')}}
 async function saveScheme(){if(!schemePreview)return;setSchemeError('');setSchemeStatus('saving');try{const host=window.location.hostname||'localhost';const response=await fetch(`http://${host}:8787/api/color-scheme`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(schemePreview)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not save the color scheme');setScheme(result);setSchemePreview(null);await loadLive();setNotice('AV color scheme updated');setTimeout(()=>setNotice(''),3000)}catch(error){setSchemeError(error instanceof Error?error.message:'Could not save the color scheme')}finally{setSchemeStatus('idle')}}
 useEffect(()=>{const initial=window.setTimeout(()=>{void loadLive();void loadScheme()},0);const timer=window.setInterval(()=>void loadLive(),30000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[]);
 return <main className="app-shell">
  <header className="topbar"><button className="brand" onClick={()=>{setSelectedId(null);setView('dashboard');setQuery('')}}><span className="brand-mark">N</span><span><strong>NETGEAR</strong><small>DISCOVERY</small></span></button><nav className="view-tabs" aria-label="Dashboard views"><button className={view==='dashboard'&&!selected?'active':''} onClick={()=>{setSelectedId(null);setView('dashboard');setQuery('')}}>Dashboard</button><button className={view==='topology'&&!selected?'active':''} onClick={()=>{setSelectedId(null);setView('topology');setQuery('')}}>Topology</button></nav><div className={`network-state ${dataSource}`} title={dataSource==='live'?`Open http://${dashboardAddress} from another device`:undefined}><span className="pulse"/> {dataSource==='live'?`Dashboard · ${dashboardAddress}`:dataSource==='connecting'?'Connecting…':'Collector offline'}</div><button className="icon-button" aria-label="Open Netgear Discovery menu" onClick={()=>{setSchemeOpen(true);setSchemeSwitch(current=>current||switches[0]?.ip||'');setSchemeError('')}}>⚙</button></header>
  {!selected&&view==='topology'?<Topology switches={switches} lastUpdated={lastUpdated} onSelect={setSelectedId} vlanFor={vf}/>:!selected?<>
   <section className="hero"><div><p className="eyebrow">NETWORK OVERVIEW</p><h1>Your switches</h1><p className="subtitle">{dataSource==='live'?`Live SNMPv3 results from ${subnet}${lastUpdated?` · updated ${new Date(lastUpdated).toLocaleTimeString()}`:''}`:'Select a switch to inspect its ports and connected equipment.'}</p></div><div className="stats"><div><span className="stat-dot"/><strong>{switches.length}</strong><small>ONLINE</small></div><div><strong>{switches.flatMap(s=>s.ports).filter(p=>p.status==='up').length}</strong><small>ACTIVE PORTS</small></div><div><strong>{vlans.length}</strong><small>VLANS</small></div></div></section>
   <section className="controls"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, model or IP — try 251…" aria-label="Search switches by name, model, full IP address, or last octet"/></label><button className="scan-button" onClick={requestScan}>↻ Scan network</button></section>
   <section className="switch-grid">{matches.length?matches.map(sw=>{const layout=modelLayout(sw.model,sw.ports.length);return <button className="switch-picker" key={sw.id} onClick={()=>{setSelectedId(sw.id);setQuery('')}}><header><div><span className="online"><i/>ONLINE</span><h2>{sw.name}</h2><p>{sw.location}</p></div><span className="chevron">›</span></header><div className="mini-chassis"><div className="mini-brand">NETGEAR <span>{sw.model}</span></div><div className="mini-ports" style={{gridTemplateColumns:`repeat(${layout.columns}, minmax(0, 1fr))`}}>{panelPorts(sw.ports,layout.rows).map(p=>{const vlan=vf(p.vlan),color=vlan.color;return <i key={p.number} title={`Port ${p.number} · ${p.media.toUpperCase()} · VLAN ${p.vlan} · ${vlan.name}${p.errors?` · ${p.errors} errors`:''}`} data-errors={p.errors||undefined} style={{'--port-color':color,'--port-outline':outlineFor(color)} as React.CSSProperties} className={`${p.status} ${p.media}`}/>})}</div></div><footer><span><b>{sw.ports.filter(p=>p.status==='up').length}</b> active</span><span><b>{sw.ports.length}</b> total ports</span><span><code>{sw.ip}</code></span></footer></button>}):<div className="empty-state"><span>⌁</span><h2>No devices found</h2><p>{query?'No discovered switches match your search.':dataSource==='connecting'?'Waiting for the network scan…':dataSource==='offline'?'The collector is offline. Check the setup page and try scanning again.':`No NETGEAR switches were detected on ${subnet}.`}</p></div>}</section>
  </>:<>
   <section className="detail-head"><button className="back" onClick={()=>{setSelectedId(null);setSelectedPort(null);setQuery('')}}>← All switches</button><div className="detail-title"><div><span className="online"><i/>ONLINE</span><h1>{selected.name}</h1><p>{selected.model} · {selected.ip} · Uptime {selected.uptime}</p></div><button className="refresh" onClick={requestScan}>↻ Refresh</button></div></section>
   {(()=>{const layout=modelLayout(selected.model,selected.ports.length);return <section className="chassis-card"><div className="chassis-label"><b>NETGEAR</b><span>{selected.model}</span></div><div className="chassis-ports" style={{gridTemplateColumns:`repeat(${layout.columns}, 30px)`,minWidth:`${layout.columns*38}px`}}>{panelPorts(selected.ports,layout.rows).map(p=>{const vlan=vf(p.vlan),color=vlan.color;return <button key={p.number} onClick={()=>setSelectedPort(p)} title={`${p.media.toUpperCase()} port ${p.number} · VLAN ${p.vlan} · ${vlan.name}${p.errors?` · ${p.errors} errors`:''}`} className={`${p.status} ${p.media} ${selectedPort?.number===p.number?'selected':''}`} style={{'--port-color':color,'--port-outline':outlineFor(color)} as React.CSSProperties}><small>{p.number}</small><span className="socket"><i/><i/><i/><i/></span>{p.media==='sfp'&&<span className="media-mark">SFP</span>}<em/>{p.errors>0&&<b className="error-badge">{p.errors}</b>}</button>})}</div><div className="chassis-leds"><span><i/>PWR</span><span><i/>FAN</span><span><i/>STACK</span></div></section>})()}
   <details className="vlan-key"><summary><span><i className="legend-swatch"/>VLAN colors</span><small>{new Set(selected.ports.map(p=>p.vlan)).size} active on this switch</small><b>⌄</b></summary><div className="vlan-menu">{vlans.map(v=><span key={v.id}><i style={{background:v.color}}/><strong>VLAN {v.id}</strong><em>{v.name}</em></span>)}</div></details>
   <section className="port-section"><div className="section-bar"><div><p className="eyebrow">PORT INVENTORY</p><h2>Ports & connected equipment</h2></div><label className="search compact"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Port, device or IP — try 142…" aria-label="Search ports, devices, full IP addresses, or last octets"/></label></div><div className="port-list">{ports.map(p=><button key={p.number} onClick={()=>setSelectedPort(p)} className="port-row"><span className="port-number" style={{'--port-color':vf(p.vlan).color} as React.CSSProperties}><i/>{p.number}<small>{p.media==='sfp'?'SFP':'RJ45'}</small></span><span className="device-cell"><strong>{p.device??'No endpoint learned'}</strong><small>{p.ip??p.description??'—'} {p.mac?`· ${p.mac}`:''}</small></span><span className="metric link-metric"><small>LINK</small><b className={p.status}><i className="link-dot"/>{p.status==='up'?p.speed:'Down'}</b></span><span className="metric"><small>VLAN</small><b><i style={{background:vf(p.vlan).color}}/>{p.vlan} · {vf(p.vlan).name}</b></span><span className="metric"><small>DROPS</small><b className={p.drops>50?'warn':''}>{p.drops.toLocaleString()}</b></span><span className="metric"><small>PORT ERRORS</small><b className={p.errors?'warn':''}>{p.errors.toLocaleString()}</b></span><span className="metric optical"><small>{p.media==='sfp'?'OPTICAL RX':'POE STATUS'}</small><b>{p.media==='sfp'?(p.optical??'No DDM reading'):(p.poe??'—')}</b></span><span className="row-arrow">›</span></button>)}</div></section>
  </>}
  {selected&&selectedPort&&<div className="modal-backdrop" onMouseDown={()=>setSelectedPort(null)}><section className="port-sheet" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelectedPort(null)} aria-label="Close">×</button><div className="sheet-handle"/><p className="eyebrow">{selected.name.toUpperCase()}</p><h2>Port {selectedPort.number}</h2><div className="detail-status"><span className={`big-dot ${selectedPort.status}`}/><strong>{selectedPort.status==='up'?'Connected':'Not connected'}</strong><span>{selectedPort.speed??'Link down'}</span></div><dl><div><dt>Interface</dt><dd>{selectedPort.interface??`Port ${selectedPort.number}`}</dd></div><div><dt>Port profile</dt><dd>{selectedPort.description??'—'}</dd></div><div><dt>Discovered device</dt><dd>{selectedPort.device??'—'}</dd></div><div><dt>IP address</dt><dd>{selectedPort.ip??'—'}</dd></div><div><dt>Learned MAC</dt><dd>{selectedPort.mac??(selectedPort.learnedMacs?.length?`${selectedPort.learnedMacs.length} addresses`:'—')}</dd></div><div><dt>Packet drops</dt><dd className={selectedPort.drops>50?'warn':''}>{selectedPort.drops.toLocaleString()}</dd></div><div><dt>Port errors</dt><dd className={selectedPort.errors?'warn':''}>{selectedPort.errors}</dd></div><div><dt>{selectedPort.media==='sfp'?'Optical receive':'PoE status'}</dt><dd>{selectedPort.media==='sfp'?(selectedPort.optical??'No DDM reading'):(selectedPort.poe??'—')}</dd></div></dl><div className="vlan-control"><label>Current VLAN</label><div className="current-vlan" style={{'--vlan-color':vf(selectedPort.vlan).color} as React.CSSProperties}><i/><span><strong>VLAN {selectedPort.vlan}</strong><small>{vf(selectedPort.vlan).name}</small></span></div><small>Read-only live value reported by the switch.</small></div></section></div>}
  {schemeOpen&&<div className="modal-backdrop scheme-backdrop" onMouseDown={()=>schemeStatus==='idle'&&setSchemeOpen(false)}><section className="scheme-panel" role="dialog" aria-modal="true" aria-labelledby="scheme-title" onMouseDown={event=>event.stopPropagation()}><button className="close" onClick={()=>setSchemeOpen(false)} disabled={schemeStatus!=='idle'} aria-label="Close">×</button><p className="eyebrow">AV INTERFACE</p><h2 id="scheme-title">VLAN color scheme</h2><p className="scheme-intro">Log in to one discovered switch to preview its AV profiles. Nothing changes until you choose <strong>Use this scheme</strong>.</p>{scheme.updatedAt?<div className="saved-scheme"><span>Current server scheme</span><strong>{scheme.sourceName||scheme.sourceIp} · {scheme.profiles.length} profiles</strong><small>Saved {new Date(scheme.updatedAt).toLocaleString()}</small></div>:<div className="saved-scheme empty"><span>Current server scheme</span><strong>No saved AV color scheme</strong></div>}<div className="scheme-form"><label><span>Source switch</span><select value={schemeSwitch} onChange={event=>setSchemeSwitch(event.target.value)} disabled={schemeStatus!=='idle'}><option value="">Select a switch</option>{switches.map(item=><option key={item.ip} value={item.ip}>{item.name} · {item.model} · {item.ip}</option>)}</select></label><label><span>AV username</span><input value={avUsername} onChange={event=>setAvUsername(event.target.value)} autoComplete="username" disabled={schemeStatus!=='idle'}/></label><label><span>AV password</span><input type="password" value={avPassword} onChange={event=>setAvPassword(event.target.value)} autoComplete="current-password" placeholder="Enter switch web password" disabled={schemeStatus!=='idle'}/></label><button className="pull-scheme" onClick={pullScheme} disabled={!schemeSwitch||!avUsername||!avPassword||schemeStatus!=='idle'}>{schemeStatus==='pulling'?<><i className="spinner"/> Pulling profiles…</>:<>↓ Pull from AV interface</>}</button></div>{schemeError&&<div className="scheme-error">{schemeError}</div>}{schemePreview&&<div className="scheme-preview"><div className="preview-head"><div><span>Pull complete</span><strong>{schemePreview.sourceName} · {schemePreview.profiles.length} profiles</strong></div><button onClick={saveScheme} disabled={schemeStatus!=='idle'}>{schemeStatus==='saving'?<><i className="spinner"/> Saving…</>:'Use this scheme'}</button></div><div className="profile-grid">{schemePreview.profiles.map(profile=><div key={profile.id}><i style={{background:profile.color||colorFor(profile.id)}}/><span><strong>VLAN {profile.id}</strong><small>{profile.name}</small></span><code>{profile.color||'Auto color'}</code></div>)}</div></div>}<footer className="scheme-footer"><span>Credentials are used for this pull only and are not saved.</span><button onClick={()=>window.open(`http://${window.location.hostname||'localhost'}:8787/setup`,'_blank')}>Server settings ↗</button></footer></section></div>}
  {notice&&<div className="toast">✓ {notice}</div>}
 </main>
}
