import http from 'node:http';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import snmp from 'net-snmp';
const root=path.dirname(fileURLToPath(import.meta.url)),envPath=path.join(root,'.env');
const defaults={subnet:'10.1.0.0/24',sourceAddress:'',username:'dashboard',authProtocol:'sha512',authKey:'',privProtocol:'aes',privKey:'',port:8787,bindAddress:'0.0.0.0',pollSeconds:30};
let config={...defaults,subnet:process.env.SNMP_SUBNET||defaults.subnet,sourceAddress:process.env.SNMP_SOURCE_ADDRESS||'',username:process.env.SNMP_USERNAME||defaults.username,authProtocol:(process.env.SNMP_AUTH_PROTOCOL||defaults.authProtocol).toLowerCase(),authKey:process.env.SNMP_AUTH_KEY||'',privProtocol:(process.env.SNMP_PRIV_PROTOCOL||defaults.privProtocol).toLowerCase(),privKey:process.env.SNMP_PRIV_KEY||'',port:Number(process.env.COLLECTOR_PORT||defaults.port),bindAddress:process.env.SERVER_BIND_ADDRESS||defaults.bindAddress,pollSeconds:Number(process.env.POLL_SECONDS||defaults.pollSeconds)};
const configured=()=>config.authKey.length>=8&&config.privKey.length>=8;
const authProtocols={sha:snmp.AuthProtocols.sha,sha224:snmp.AuthProtocols.sha224,sha256:snmp.AuthProtocols.sha256,sha384:snmp.AuthProtocols.sha384,sha512:snmp.AuthProtocols.sha512};
const privProtocols={aes:snmp.PrivProtocols.aes,aes128:snmp.PrivProtocols.aes};
const snmpUser=()=>({name:config.username,level:snmp.SecurityLevel.authPriv,authProtocol:authProtocols[config.authProtocol]??snmp.AuthProtocols.sha512,authKey:config.authKey,privProtocol:privProtocols[config.privProtocol]??snmp.PrivProtocols.aes,privKey:config.privKey});
const O={sysDescr:'1.3.6.1.2.1.1.1.0',sysUpTime:'1.3.6.1.2.1.1.3.0',sysName:'1.3.6.1.2.1.1.5.0',ifDescr:'1.3.6.1.2.1.2.2.1.2',ifType:'1.3.6.1.2.1.2.2.1.3',ifOper:'1.3.6.1.2.1.2.2.1.8',inDiscards:'1.3.6.1.2.1.2.2.1.13',inErrors:'1.3.6.1.2.1.2.2.1.14',outDiscards:'1.3.6.1.2.1.2.2.1.19',outErrors:'1.3.6.1.2.1.2.2.1.20',ifName:'1.3.6.1.2.1.31.1.1.1.1',ifHighSpeed:'1.3.6.1.2.1.31.1.1.1.15',ifAlias:'1.3.6.1.2.1.31.1.1.1.18',bridgeMap:'1.3.6.1.2.1.17.1.4.1.2',pvid:'1.3.6.1.2.1.17.7.1.4.5.1.1'};
let state={status:configured()?'starting':'setup_required',subnet:config.subnet,lastUpdated:null,switches:[],error:null};let scanning=false;
const value=v=>Buffer.isBuffer(v)?v.toString('utf8').replace(/\0/g,'').trim():v,indexOf=(oid,base)=>Number(oid.slice(base.length+1).split('.').pop());
function session(ip){return snmp.createV3Session(ip,snmpUser(),{port:161,retries:0,timeout:900,transport:'udp4',sourceAddress:config.sourceAddress||undefined,backwardsGetNexts:true,idBitsSize:32})}
function get(ip,oids){return new Promise((resolve,reject)=>{const s=session(ip);s.get(oids,(e,v)=>{s.close();e?reject(e):resolve(v)})})}
function walk(ip,base){return new Promise((resolve,reject)=>{const s=session(ip),rows=[];s.subtree(base,20,vbs=>{for(const vb of vbs)if(!snmp.isVarbindError(vb))rows.push(vb)},e=>{s.close();e?reject(e):resolve(rows)})})}
function hosts(cidr){const [raw,bitsText]=cidr.split('/'),bits=Number(bitsText);if(bits<16||bits>30)throw new Error('Subnet must be between /16 and /30');const parts=raw.split('.').map(Number);if(parts.length!==4||parts.some(n=>!Number.isInteger(n)||n<0||n>255))throw new Error('Enter a valid IPv4 subnet');const n=((parts[0]<<24)|(parts[1]<<16)|(parts[2]<<8)|parts[3])>>>0,mask=(0xffffffff<<(32-bits))>>>0,network=n&mask,size=2**(32-bits),out=[];for(let i=1;i<size-1;i++){const x=(network+i)>>>0;out.push(`${x>>>24}.${(x>>>16)&255}.${(x>>>8)&255}.${x&255}`)}return out}
async function discover(ip){try{const v=await get(ip,[O.sysDescr,O.sysName,O.sysUpTime]);const descr=String(value(v[0].value)||'');if(!/netgear|m4[0-9]{3}/i.test(descr))return null;return {ip,descr,name:String(value(v[1].value)||ip),ticks:Number(v[2].value||0)}}catch{return null}}
async function pool(items,limit,work){const results=[];let next=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(next<items.length){const result=await work(items[next++]);if(result)results.push(result)}}));return results}
const table=rows=>Object.fromEntries(rows.map(r=>[indexOf(r.oid,r.base),value(r.value)]));
async function inspect(sw){const bases=[O.ifDescr,O.ifType,O.ifOper,O.inDiscards,O.inErrors,O.outDiscards,O.outErrors,O.ifName,O.ifHighSpeed,O.ifAlias,O.bridgeMap,O.pvid],result=await Promise.all(bases.map(async base=>(await walk(sw.ip,base)).map(r=>({...r,base}))));const [descr,type,oper,inDrop,inErr,outDrop,outErr,names,speeds,aliases,bridge,pvids]=result.map(table),ifToPvid={};for(const [bridgePort,ifIndex] of Object.entries(bridge))ifToPvid[Number(ifIndex)]=Number(pvids[Number(bridgePort)]||1);const physical=Object.keys(names).map(Number).filter(i=>[6,117].includes(Number(type[i]))&&/\d/.test(String(names[i]||descr[i]||''))).sort((a,b)=>a-b);return {id:sw.ip.replaceAll('.','-'),name:sw.name,model:(sw.descr.match(/M4\d{3}[-\w+]*/i)||['NETGEAR AV'])[0],ip:sw.ip,location:'Discovered switch',uptime:formatUptime(sw.ticks),ports:physical.map((ifIndex,pos)=>{const label=String(names[ifIndex]||descr[ifIndex]),number=Number((label.match(/\d+(?!.*\d)/)||[pos+1])[0]),speed=Number(speeds[ifIndex]||0);return {number,status:Number(oper[ifIndex])===1?'up':'down',speed:speed?`${speed>=1000?speed/1000:speed}${speed>=1000?'G':'M'}`:undefined,vlan:ifToPvid[ifIndex]||1,device:String(aliases[ifIndex]||'').trim()||undefined,drops:Number(inDrop[ifIndex]||0)+Number(outDrop[ifIndex]||0),errors:Number(inErr[ifIndex]||0)+Number(outErr[ifIndex]||0),media:/sfp|fiber|xg/i.test(label)?'sfp':'copper'}})}}
function formatUptime(ticks){const sec=Math.floor(ticks/100),d=Math.floor(sec/86400),h=Math.floor(sec%86400/3600);return `${d}d ${String(h).padStart(2,'0')}h`}
async function scan(){if(scanning||!configured())return;scanning=true;try{state={...state,status:'scanning',subnet:config.subnet,error:null};const found=await pool(hosts(config.subnet),32,discover),switches=[];for(const sw of found){try{switches.push(await inspect(sw))}catch(e){console.warn(`Could not read interfaces from ${sw.ip}: ${e.message}`)}}state={status:'online',subnet:config.subnet,lastUpdated:new Date().toISOString(),switches:switches.sort((a,b)=>a.ip.localeCompare(b.ip,undefined,{numeric:true})),error:null};console.log(`SNMP scan complete: ${switches.length} NETGEAR switch(es) found`)}catch(e){state={...state,status:'error',error:e.message,lastUpdated:new Date().toISOString()}}finally{scanning=false}}
const local=req=>['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress||'');
const send=(res,status,data,type='application/json')=>{res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type'});res.end(type==='application/json'?JSON.stringify(data):data)};
const readBody=req=>new Promise((resolve,reject)=>{let body='';req.on('data',c=>{body+=c;if(body.length>65536)reject(new Error('Request too large'))});req.on('end',()=>{try{resolve(JSON.parse(body))}catch{reject(new Error('Invalid settings'))}})});
function publicConfig(){return {subnet:config.subnet,sourceAddress:config.sourceAddress,username:config.username,authProtocol:config.authProtocol,privProtocol:config.privProtocol,port:config.port,bindAddress:config.bindAddress,pollSeconds:config.pollSeconds,hasAuthKey:!!config.authKey,hasPrivKey:!!config.privKey}}
function interfaces(){return Object.entries(os.networkInterfaces()).flatMap(([name,addresses])=>(addresses||[]).filter(a=>(a.family==='IPv4'||a.family===4)&&!a.internal).map(a=>({name,address:a.address,netmask:a.netmask,cidr:a.cidr||`${a.address}/24`,mac:a.mac}))).sort((a,b)=>a.name.localeCompare(b.name)||a.address.localeCompare(b.address,undefined,{numeric:true}))}
function saveConfig(next){hosts(next.subnet);if(!next.username?.trim())throw new Error('SNMPv3 username is required');const authKey=next.authKey?.trim()||config.authKey,privKey=next.privKey?.trim()||config.privKey;if(authKey.length<8||privKey.length<8)throw new Error('Both SNMPv3 keys must be at least 8 characters');const oldBind=config.bindAddress;config={...config,subnet:next.subnet.trim(),sourceAddress:(next.sourceAddress||'').trim(),username:next.username.trim(),authProtocol:'sha512',authKey,privProtocol:'aes',privKey,bindAddress:(next.bindAddress||'0.0.0.0').trim(),pollSeconds:Math.max(10,Number(next.pollSeconds)||30)};const lines=[`SNMP_SUBNET=${config.subnet}`,`SNMP_SOURCE_ADDRESS=${config.sourceAddress}`,`SNMP_USERNAME=${config.username}`,`SNMP_AUTH_PROTOCOL=${config.authProtocol}`,`SNMP_AUTH_KEY=${config.authKey}`,`SNMP_PRIV_PROTOCOL=${config.privProtocol}`,`SNMP_PRIV_KEY=${config.privKey}`,`COLLECTOR_PORT=${config.port}`,`SERVER_BIND_ADDRESS=${config.bindAddress}`,`POLL_SECONDS=${config.pollSeconds}`];fs.writeFileSync(envPath,lines.join('\n')+'\n',{mode:0o600});state={...state,status:'starting',subnet:config.subnet,error:null};scan();return oldBind!==config.bindAddress}
const server=http.createServer(async(req,res)=>{
 if(req.method==='OPTIONS')return send(res,204,{});
 const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);
 if(url.pathname==='/api/switches')return send(res,200,state);
 if(url.pathname==='/api/scan'&&req.method==='POST'){scan();return send(res,202,{status:configured()?'scanning':'setup_required'})}
 if(url.pathname==='/api/health')return send(res,200,{ok:true,status:state.status,subnet:config.subnet});
 if(url.pathname==='/api/interfaces'){if(!local(req))return send(res,403,{error:'Interface discovery is available only on the Windows server.'});return send(res,200,{interfaces:interfaces()})}
 if(url.pathname==='/setup'||url.pathname==='/setup.css'||url.pathname==='/setup.js'){
  if(!local(req))return send(res,403,'Settings are available only on the Windows server.','text/plain');
  const file=url.pathname==='/setup'?'setup.html':url.pathname.slice(1);
  return send(res,200,fs.readFileSync(path.join(root,file)),file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':'text/html');
 }
 if(url.pathname==='/api/config'){
  if(!local(req))return send(res,403,{error:'Settings are available only on the Windows server.'});
  if(req.method==='GET')return send(res,200,publicConfig());
  if(req.method==='POST'){
   try{const restartRequired=saveConfig(await readBody(req));return send(res,200,{ok:true,restartRequired,status:'Scanning network…'})}
   catch(e){return send(res,400,{error:e.message})}
  }
 }
 return send(res,404,{error:'Not found'});
});
server.listen(config.port,config.bindAddress,()=>{console.log(`NETGEAR AV collector listening on ${config.bindAddress}:${config.port}`);if(configured())scan();else console.log(`Complete setup at http://localhost:${config.port}/setup`)});setInterval(scan,Math.max(10,config.pollSeconds)*1000);
