import http from 'node:http';
import snmp from 'net-snmp';

const config={subnet:process.env.SNMP_SUBNET||'10.1.0.0/24',sourceAddress:process.env.SNMP_SOURCE_ADDRESS||undefined,username:process.env.SNMP_USERNAME||'dashboard',authProtocol:(process.env.SNMP_AUTH_PROTOCOL||'sha512').toLowerCase(),authKey:process.env.SNMP_AUTH_KEY||'',privProtocol:(process.env.SNMP_PRIV_PROTOCOL||'aes').toLowerCase(),privKey:process.env.SNMP_PRIV_KEY||'',port:Number(process.env.COLLECTOR_PORT||8787),bindAddress:process.env.SERVER_BIND_ADDRESS||'0.0.0.0',pollMs:Number(process.env.POLL_SECONDS||30)*1000};
if(!config.authKey||!config.privKey){console.error('SNMP credentials are not configured. Run scripts/setup-windows.ps1 first.');process.exit(1)}
const authProtocols={sha:snmp.AuthProtocols.sha,sha224:snmp.AuthProtocols.sha224,sha256:snmp.AuthProtocols.sha256,sha384:snmp.AuthProtocols.sha384,sha512:snmp.AuthProtocols.sha512};
const privProtocols={aes:snmp.PrivProtocols.aes,aes128:snmp.PrivProtocols.aes,aes192:snmp.PrivProtocols.aes192b,aes256:snmp.PrivProtocols.aes256b};
const user={name:config.username,level:snmp.SecurityLevel.authPriv,authProtocol:authProtocols[config.authProtocol]??snmp.AuthProtocols.sha512,authKey:config.authKey,privProtocol:privProtocols[config.privProtocol]??snmp.PrivProtocols.aes,privKey:config.privKey};
const O={sysDescr:'1.3.6.1.2.1.1.1.0',sysUpTime:'1.3.6.1.2.1.1.3.0',sysName:'1.3.6.1.2.1.1.5.0',ifDescr:'1.3.6.1.2.1.2.2.1.2',ifType:'1.3.6.1.2.1.2.2.1.3',ifOper:'1.3.6.1.2.1.2.2.1.8',inDiscards:'1.3.6.1.2.1.2.2.1.13',inErrors:'1.3.6.1.2.1.2.2.1.14',outDiscards:'1.3.6.1.2.1.2.2.1.19',outErrors:'1.3.6.1.2.1.2.2.1.20',ifName:'1.3.6.1.2.1.31.1.1.1.1',ifHighSpeed:'1.3.6.1.2.1.31.1.1.1.15',ifAlias:'1.3.6.1.2.1.31.1.1.1.18',bridgeMap:'1.3.6.1.2.1.17.1.4.1.2',pvid:'1.3.6.1.2.1.17.7.1.4.5.1.1'};
let state={status:'starting',subnet:config.subnet,lastUpdated:null,switches:[],error:null};let scanning=false;
const value=v=>Buffer.isBuffer(v)?v.toString('utf8').replace(/\0/g,'').trim():v;
const indexOf=(oid,base)=>Number(oid.slice(base.length+1).split('.').pop());
function session(ip){return snmp.createV3Session(ip,user,{port:161,retries:0,timeout:900,transport:'udp4',sourceAddress:config.sourceAddress,backwardsGetNexts:true,idBitsSize:32})}
function get(ip,oids){return new Promise((resolve,reject)=>{const s=session(ip);s.get(oids,(e,v)=>{s.close();e?reject(e):resolve(v)})})}
function walk(ip,base){return new Promise((resolve,reject)=>{const s=session(ip),rows=[];s.subtree(base,20,vbs=>{for(const vb of vbs)if(!snmp.isVarbindError(vb))rows.push(vb)},e=>{s.close();e?reject(e):resolve(rows)})})}
function hosts(cidr){const [raw,bitsText]=cidr.split('/'),bits=Number(bitsText);if(bits<16||bits>30)throw new Error('Subnet must be between /16 and /30');const parts=raw.split('.').map(Number);const n=((parts[0]<<24)|(parts[1]<<16)|(parts[2]<<8)|parts[3])>>>0,mask=(0xffffffff<<(32-bits))>>>0,network=n&mask,size=2**(32-bits),out=[];for(let i=1;i<size-1;i++){const x=(network+i)>>>0;out.push(`${x>>>24}.${(x>>>16)&255}.${(x>>>8)&255}.${x&255}`)}return out}
async function discover(ip){try{const v=await get(ip,[O.sysDescr,O.sysName,O.sysUpTime]);const descr=String(value(v[0].value)||'');if(!/netgear|m4[0-9]{3}/i.test(descr))return null;return {ip,descr,name:String(value(v[1].value)||ip),ticks:Number(v[2].value||0)}}catch{return null}}
async function pool(items,limit,work){const results=[];let next=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(next<items.length){const i=next++;const result=await work(items[i]);if(result)results.push(result)}}));return results}
const table=rows=>Object.fromEntries(rows.map(r=>[indexOf(r.oid,r.base),value(r.value)]));
async function inspect(sw){const bases=[O.ifDescr,O.ifType,O.ifOper,O.inDiscards,O.inErrors,O.outDiscards,O.outErrors,O.ifName,O.ifHighSpeed,O.ifAlias,O.bridgeMap,O.pvid];const result=await Promise.all(bases.map(async base=>(await walk(sw.ip,base)).map(r=>({...r,base}))));const [descr,type,oper,inDrop,inErr,outDrop,outErr,names,speeds,aliases,bridge,pvids]=result.map(table);const ifToPvid={};for(const [bridgePort,ifIndex] of Object.entries(bridge))ifToPvid[Number(ifIndex)]=Number(pvids[Number(bridgePort)]||1);const physical=Object.keys(names).map(Number).filter(i=>[6,117].includes(Number(type[i]))&&/\d/.test(String(names[i]||descr[i]||''))).sort((a,b)=>a-b);return {id:sw.ip.replaceAll('.','-'),name:sw.name,model:(sw.descr.match(/M4\d{3}[-\w+]*/i)||['NETGEAR AV'])[0],ip:sw.ip,location:'Discovered switch',uptime:formatUptime(sw.ticks),ports:physical.map((ifIndex,pos)=>{const label=String(names[ifIndex]||descr[ifIndex]),number=Number((label.match(/\d+(?!.*\d)/)||[pos+1])[0]),speed=Number(speeds[ifIndex]||0);return {number,status:Number(oper[ifIndex])===1?'up':'down',speed:speed?`${speed>=1000?speed/1000:speed}${speed>=1000?'G':'M'}`:undefined,vlan:ifToPvid[ifIndex]||1,device:String(aliases[ifIndex]||'').trim()||undefined,drops:Number(inDrop[ifIndex]||0)+Number(outDrop[ifIndex]||0),errors:Number(inErr[ifIndex]||0)+Number(outErr[ifIndex]||0),media:/sfp|fiber|xg/i.test(label)?'sfp':'copper'}})}}
function formatUptime(ticks){const sec=Math.floor(ticks/100),d=Math.floor(sec/86400),h=Math.floor(sec%86400/3600);return `${d}d ${String(h).padStart(2,'0')}h`}
async function scan(){if(scanning)return;scanning=true;try{state={...state,status:'scanning',error:null};const found=await pool(hosts(config.subnet),32,discover);const switches=[];for(const sw of found){try{switches.push(await inspect(sw))}catch(e){console.warn(`Could not read interfaces from ${sw.ip}: ${e.message}`)}}state={status:'online',subnet:config.subnet,lastUpdated:new Date().toISOString(),switches:switches.sort((a,b)=>a.ip.localeCompare(b.ip,undefined,{numeric:true})),error:null};console.log(`SNMP scan complete: ${switches.length} NETGEAR switch(es) found`)}catch(e){state={...state,status:'error',error:e.message,lastUpdated:new Date().toISOString()};console.error(e)}finally{scanning=false}}
const server=http.createServer((req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Content-Type','application/json');if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}if(req.url==='/api/switches'){res.end(JSON.stringify(state));return}if(req.url==='/api/scan'&&req.method==='POST'){scan();res.writeHead(202);res.end(JSON.stringify({status:'scanning'}));return}if(req.url==='/api/health'){res.end(JSON.stringify({ok:true,status:state.status,subnet:config.subnet}));return}res.writeHead(404);res.end(JSON.stringify({error:'Not found'}))});
server.listen(config.port,config.bindAddress,()=>{console.log(`NETGEAR AV collector listening on ${config.bindAddress}:${config.port}; scanning ${config.subnet}${config.sourceAddress?` from ${config.sourceAddress}`:''}`);scan();setInterval(scan,config.pollMs)});
